server:
  port: 8081

dubbo:
  application:
    name: order-service-consumer
  registry:
    address: zookeeper://127.0.0.1:2181
  monitor:
    protocol: registry
#  consumer: #配置这个微服务中的所有消费者接口都不启动时检查
#    check: false
#    timeout: 3000 #这里可以配置超时时间,默认是超时一秒钟,才报错,可以配置的更大

